In [242]:
import pandas as pd
data = pd.read_csv('../data/monthly_county_losses_sub.csv')
df = pd.DataFrame(data)

In [243]:
#number one
df = df.set_index(df.county_name) #setting index = county name
df[:5]

,Unnamed: 0,state,county_name,fips_code,hazard_code_desc,year,month,property_damage,crop_damage,fatalities,injuries,num_records,population,county_id
county_name,,,,,,,,,,,,,,
Autauga,0,AL,Autauga,1001,Severe Storm/Thunder Storm,1961,2,59156.670000,59156.670000,0.0,0.000000,1,19311,1
Autauga,1,AL,Autauga,1001,Severe Storm/Thunder Storm,1961,12,66058.220000,6605.800000,0.0,0.000000,1,19311,1
Autauga,2,AL,Autauga,1001,Winter Weather,1961,1,16925.390000,5915.670000,0.0,0.000000,2,19311,1
Autauga,3,AL,Autauga,1001,Hail,1962,4,1952.303333,1952.303333,0.0,0.003333,1,19883,1
Autauga,4,AL,Autauga,1001,Severe Storm/Thunder Storm,1962,4,1952.303333,1952.303333,0.0,0.003333,1,19883,1

In [244]:
#number two
tornados = df.hazard_code_desc == 'Tornado'
tornado_kills = df[tornados].fatalities.sum()               #how many people killed by tornado
print("Tornado:",tornado_kills)
hurrtrop = df.hazard_code_desc == 'Hurricane/Tropical Storm'
hurrtrop_kills = df[hurrtrop].fatalities.sum()              #how many people killed by hurricane/tropical storm
print("Hurricane/Tropical storm:",hurrtrop_kills)

Tornado: 4012.4249992
Hurricane/Tropical storm: 1545.59333329

In [245]:
#number three
import numpy as np
hazard_codes = ['Avalanche', 'Coastal', 'Drought', 'Earthquake', 'Flooding', 'Fog', 'Hail', 'Heat', 'Hurricane/Tropical Storm', 'Landslide',
 'Lightning', 'Severe Storm/Thunder Storm', 'Tornado', 'Tsunami/Seiche', 'Volcano', 'Wildfire', 'Wind', 'Winter Weather']

sums = []
big = 0
for kind in hazard_codes:
    if df[df.hazard_code_desc==kind].fatalities.sum() > big:
        big = df[df.hazard_code_desc==kind].fatalities.sum()   #choosing the largest number of fatalities
    sums.append(df[df.hazard_code_desc==kind].fatalities.sum())
print(hazard_codes[sums.index(big)]) #printing the deadliest type

Heat

In [246]:
#number four
bvtorns = (df.hazard_code_desc == 'Tornado')&(df.county_name == 'Buena Vista') #choosing tornados in BV county
median = df[bvtorns].property_damage.median()
print("Median:",median)
mean  = df[bvtorns].property_damage.mean()
print("Mean:",mean)

Median: 206791.8
Mean: 432182.616

In [247]:
#number five
df['property_damage_2017'] = df.property_damage * 1.03  #1.03 is the conversion rate
df['crop_damage_2017'] = df.crop_damage * 1.03

df[:5]

,Unnamed: 0,state,county_name,fips_code,hazard_code_desc,year,month,property_damage,crop_damage,fatalities,injuries,num_records,population,county_id,property_damage_2017,crop_damage_2017
county_name,,,,,,,,,,,,,,,,
Autauga,0,AL,Autauga,1001,Severe Storm/Thunder Storm,1961,2,59156.670000,59156.670000,0.0,0.000000,1,19311,1,60931.370100,60931.370100
Autauga,1,AL,Autauga,1001,Severe Storm/Thunder Storm,1961,12,66058.220000,6605.800000,0.0,0.000000,1,19311,1,68039.966600,6803.974000
Autauga,2,AL,Autauga,1001,Winter Weather,1961,1,16925.390000,5915.670000,0.0,0.000000,2,19311,1,17433.151700,6093.140100
Autauga,3,AL,Autauga,1001,Hail,1962,4,1952.303333,1952.303333,0.0,0.003333,1,19883,1,2010.872433,2010.872433
Autauga,4,AL,Autauga,1001,Severe Storm/Thunder Storm,1962,4,1952.303333,1952.303333,0.0,0.003333,1,19883,1,2010.872433,2010.872433

In [248]:
#number six
df['fatalities_per_capita'] = df.fatalities/df.population
df['injuries_per_capita'] = df.injuries/df.population     
df[:5]

,Unnamed: 0,state,county_name,fips_code,hazard_code_desc,year,month,property_damage,crop_damage,fatalities,injuries,num_records,population,county_id,property_damage_2017,crop_damage_2017,fatalities_per_capita,injuries_per_capita
county_name,,,,,,,,,,,,,,,,,,
Autauga,0,AL,Autauga,1001,Severe Storm/Thunder Storm,1961,2,59156.670000,59156.670000,0.0,0.000000,1,19311,1,60931.370100,60931.370100,0.0,0.000000e+00
Autauga,1,AL,Autauga,1001,Severe Storm/Thunder Storm,1961,12,66058.220000,6605.800000,0.0,0.000000,1,19311,1,68039.966600,6803.974000,0.0,0.000000e+00
Autauga,2,AL,Autauga,1001,Winter Weather,1961,1,16925.390000,5915.670000,0.0,0.000000,2,19311,1,17433.151700,6093.140100,0.0,0.000000e+00
Autauga,3,AL,Autauga,1001,Hail,1962,4,1952.303333,1952.303333,0.0,0.003333,1,19883,1,2010.872433,2010.872433,0.0,1.676472e-07
Autauga,4,AL,Autauga,1001,Severe Storm/Thunder Storm,1962,4,1952.303333,1952.303333,0.0,0.003333,1,19883,1,2010.872433,2010.872433,0.0,1.676472e-07

In [249]:
#number seven
df = df.sort_values(by = 'fatalities_per_capita',ascending = False)   
df[:5]

,Unnamed: 0,state,county_name,fips_code,hazard_code_desc,year,month,property_damage,crop_damage,fatalities,injuries,num_records,population,county_id,property_damage_2017,crop_damage_2017,fatalities_per_capita,injuries_per_capita
county_name,,,,,,,,,,,,,,,,,,
Kalawao,120504,HI,Kalawao,15005,Coastal,1997,1,0.00,0.0,4.0,0.0,1,76,519,0.0000,0.0,0.052632,0.000000
Kalawao,120494,HI,Kalawao,15005,Flooding,1994,3,79965.25,0.0,2.0,0.0,1,101,519,82364.2075,0.0,0.019802,0.000000
Kalawao,120505,HI,Kalawao,15005,Coastal,1997,12,0.00,0.0,1.0,1.0,1,76,519,0.0000,0.0,0.013158,0.013158
Loving,759721,TX,Loving,48301,Wind,1966,4,0.00,0.0,2.0,0.0,1,189,2646,0.0000,0.0,0.010582,0.000000
Loving,759720,TX,Loving,48301,Hail,1966,4,0.00,0.0,2.0,0.0,1,189,2646,0.0000,0.0,0.010582,0.000000

In [250]:
#number eight
fatinj = df['fatalities'].corr(df['injuries'])
fatprop = df['fatalities'].corr(df['property_damage'])  #correlation coefficient between variables using pandas
print("Fatalities vs injuries:",fatinj)
print("Fatalities vs propery damage:",fatprop)

Fatalities vs injuries: 0.151444615333
Fatalities vs propery damage: 0.203381093581

In [251]:
#number nine
tornados = df.hazard_code_desc == 'Tornado'
tornfatinj = df[tornados].fatalities.corr(df[tornados].injuries)            #correlation except only for tornado incidents
print("Tornados only for fatalities vs injuries:",tornfatinj)
tornfatprop = df[tornados].fatalities.corr(df[tornados].property_damage)
print("Tornados only for fatalities vs property damage:",tornfatprop)

Tornados only for fatalities vs injuries: 0.628213703783
Tornados only for fatalities vs property damage: 0.584267571801